import type { Project } from './types';

export const projects: Project[] = [
    {
        id: '1',
        projectId: 'PN0001245',
        name: 'Furniture Parts',
        description: 'Կahuyqi patvereri karavaryum',
        reporterName: 'Aram Petrosyan',
        reporterColor: '#4361EE',
        reporterInitials: 'AP',
        priority: 'High',
        deadline: '2026-06-30',
        createdAt: '2026-05-01',
        assignees: [
            { id: 'a1', name: 'Aram Petrosyan', color: '#4361EE', initials: 'AP', role: 'Varapet' },
            { id: 'a2', name: 'Nare Hakobyan', color: '#FF6B9D', initials: 'NH', role: 'Karogh' },
            { id: 'a3', name: 'Karen Sargsyan', color: '#4ECDC4', initials: 'KS', role: 'Ktrogh' },
            { id: 'a4', name: 'Ani Grigoryan', color: '#F0A500', initials: 'AG', role: 'Karogh' },
            { id: 'a5', name: 'Artur Avetisyan', color: '#96CEB4', initials: 'AA', role: 'Ashakert' },
        ],
        tasks: [

            // ── ACTIVE ──────────────────────────────────────────────────────────────

            // 1 · done · High
            {
                id: 't1',
                taskId: 'PN0001245',
                name: 'Divan "Riviera" — Akobyan A.',
                description: 'Erkteghi bazmots, kanak bambak, amur kofu',
                estimate: '3d',
                spentTime: '3d',
                loggedTime: '3d',
                originalEstimate: '3d',
                status: 'done',
                section: 'active',
                priority: 'High',
                group: 'Ս',
                assigneeColor: '#4361EE',
                assigneeInitials: 'AP',
                assigneeName: 'Aram Petrosyan',
                reporterName: 'Aram Petrosyan',
                reporterColor: '#4361EE',
                reporterInitials: 'AP',
                deadline: '2026-05-08',
                createdAt: '2026-05-01',
                editedAt: '2026-05-08',
                client: 'Akobyan Anna',
                phone: '+37491234567',
                acceptanceDate: '2026-05-01',
                deliveryAddress: 'Yerevan, Mashtots 14, apt 3',
                model: 'Riviera 2-seat sofa',
                dimensions: '190×90×85 sm',
                fabricType: 'Բամբակ',
                softness: 'Փափուկ',
                price: '85,000 ֏',
                advancePayment: '40,000 ֏',
                finalPayment: '45,000 ֏',
                notes: 'Hetdards ushadrelu e pahelu',
                startDay: 1,
                endDay: 8,
            },

            // 2 · done · Medium
            {
                id: 't2',
                taskId: 'PN0001245',
                name: 'Berger kreslо — Danielyan G.',
                description: 'Flanel tsatskov, krem guyn',
                estimate: '2d',
                spentTime: '2d',
                loggedTime: '2d',
                originalEstimate: '2d',
                status: 'done',
                section: 'active',
                priority: 'Medium',
                group: 'Ա',
                assigneeColor: '#4ECDC4',
                assigneeInitials: 'KS',
                assigneeName: 'Karen Sargsyan',
                reporterName: 'Aram Petrosyan',
                reporterColor: '#4361EE',
                reporterInitials: 'AP',
                deadline: '2026-05-10',
                createdAt: '2026-05-03',
                editedAt: '2026-05-10',
                client: 'Danielyan Grigor',
                phone: '+37493456789',
                acceptanceDate: '2026-05-03',
                deliveryAddress: 'Yerevan, Komitas 55, apt 12',
                model: 'Berger armchair',
                dimensions: '80×85×100 sm',
                fabricType: 'Ֆլանել',
                softness: 'Միջին',
                price: '42,000 ֏',
                advancePayment: '20,000 ֏',
                finalPayment: '22,000 ֏',
                notes: '',
                startDay: 3,
                endDay: 10,
            },

            // 3 · in_progress · High
            {
                id: 't3',
                taskId: 'PN0001245',
                name: 'Divan-knizhka — Margaryan L.',
                description: 'Poliester ko, mug-kazin guyn',
                estimate: '4d',
                spentTime: '2d',
                loggedTime: '2d',
                originalEstimate: '4d',
                status: 'in_progress',
                section: 'active',
                priority: 'High',
                group: 'Ա',
                assigneeColor: '#4361EE',
                assigneeInitials: 'AP',
                assigneeName: 'Aram Petrosyan',
                reporterName: 'Aram Petrosyan',
                reporterColor: '#4361EE',
                reporterInitials: 'AP',
                deadline: '2026-05-20',
                createdAt: '2026-05-10',
                client: 'Margaryan Lilit',
                phone: '+37494567890',
                acceptanceDate: '2026-05-10',
                deliveryAddress: 'Yerevan, Tigranyan 7, apt 1',
                model: 'Sofa-book folding',
                dimensions: '200×95×90 sm',
                fabricType: 'Պոլիեսթեր',
                softness: 'Կոշտ',
                price: '110,000 ֏',
                advancePayment: '55,000 ֏',
                finalPayment: '55,000 ֏',
                notes: 'Mekhanism sdarkel minchev handes kariq e',
                startDay: 10,
                endDay: 20,
            },

            // 4 · in_progress · Medium
            {
                id: 't4',
                taskId: 'PN0001245',
                name: 'Ankunayin divan — Sahakyan M.',
                description: 'Metaks ktor, L-dzev, dzakh ankyun',
                estimate: '5d',
                spentTime: '2d',
                loggedTime: '2d',
                originalEstimate: '5d',
                status: 'in_progress',
                section: 'active',
                priority: 'Medium',
                group: 'Ս',
                assigneeColor: '#FF6B9D',
                assigneeInitials: 'NH',
                assigneeName: 'Nare Hakobyan',
                reporterName: 'Aram Petrosyan',
                reporterColor: '#4361EE',
                reporterInitials: 'AP',
                deadline: '2026-05-22',
                createdAt: '2026-05-12',
                client: 'Sahakyan Meri',
                phone: '+37495678901',
                acceptanceDate: '2026-05-12',
                deliveryAddress: 'Yerevan, Baghramyan 22, apt 8',
                model: 'Corner sofa L-shape',
                dimensions: '260×170×85 sm',
                fabricType: 'Մետաքս',
                softness: 'Շատ փափուկ',
                price: '165,000 ֏',
                advancePayment: '80,000 ֏',
                finalPayment: '85,000 ֏',
                notes: 'Dzakh ankyun — kliyentis pahanjov',
                startDay: 12,
                endDay: 22,
            },

            // 5 · in_progress · Low
            {
                id: 't5',
                taskId: 'PN0001245',
                name: 'Pouf kvadratayin — Hovhannisyan S.',
                description: 'Saten tsatskov, voske guyn',
                estimate: '1d',
                spentTime: '0.5d',
                loggedTime: '0.5d',
                originalEstimate: '1d',
                status: 'in_progress',
                section: 'active',
                priority: 'Low',
                group: 'Ա',
                assigneeColor: '#96CEB4',
                assigneeInitials: 'AA',
                assigneeName: 'Artur Avetisyan',
                reporterName: 'Aram Petrosyan',
                reporterColor: '#4361EE',
                reporterInitials: 'AP',
                deadline: '2026-05-16',
                createdAt: '2026-05-14',
                client: 'Hovhannisyan Seda',
                phone: '+37496789012',
                acceptanceDate: '2026-05-14',
                deliveryAddress: 'Yerevan, Abovyan 3, apt 21',
                model: 'Square pouf 50x50',
                dimensions: '50×50×45 sm',
                fabricType: 'Սաթեն',
                softness: 'Փափուկ',
                price: '18,000 ֏',
                advancePayment: '9,000 ֏',
                finalPayment: '9,000 ֏',
                notes: '',
                startDay: 14,
                endDay: 16,
            },

            // 6 · in_review · High
            {
                id: 't6',
                taskId: 'PN0001245',
                name: 'Divan "Klassik" — Petrosyan V.',
                description: 'Kashmir tsatskov, kazin, kavor otnakernerov',
                estimate: '4d',
                spentTime: '4d',
                loggedTime: '4d',
                originalEstimate: '4d',
                status: 'in_review',
                section: 'active',
                priority: 'High',
                group: 'Ս',
                assigneeColor: '#4ECDC4',
                assigneeInitials: 'KS',
                assigneeName: 'Karen Sargsyan',
                reporterName: 'Aram Petrosyan',
                reporterColor: '#4361EE',
                reporterInitials: 'AP',
                deadline: '2026-05-18',
                createdAt: '2026-05-07',
                editedAt: '2026-05-15',
                client: 'Petrosyan Varduhi',
                phone: '+37497890123',
                acceptanceDate: '2026-05-07',
                deliveryAddress: 'Yerevan, Hanrapetutyan 40, apt 5',
                model: 'Classic 3-seat sofa',
                dimensions: '220×100×90 sm',
                fabricType: 'Քաշմիր',
                softness: 'Միջին',
                price: '130,000 ֏',
                advancePayment: '65,000 ֏',
                finalPayment: '65,000 ֏',
                notes: 'Otnakner — mug ynkuyz, lakavorel minchev handes',
                startDay: 7,
                endDay: 18,
            },

            // 7 · in_review · Medium
            {
                id: 't7',
                taskId: 'PN0001245',
                name: 'Kreslo-khachakhag — Ghazaryan K.',
                description: 'Ktav tsatskov, uzghadzik tev',
                estimate: '2d',
                spentTime: '2d',
                loggedTime: '2d',
                originalEstimate: '2d',
                status: 'in_review',
                section: 'active',
                priority: 'Medium',
                group: 'Ա',
                assigneeColor: '#F0A500',
                assigneeInitials: 'AG',
                assigneeName: 'Ani Grigoryan',
                reporterName: 'Aram Petrosyan',
                reporterColor: '#4361EE',
                reporterInitials: 'AP',
                deadline: '2026-05-17',
                createdAt: '2026-05-09',
                editedAt: '2026-05-14',
                client: 'Ghazaryan Knarik',
                phone: '+37498901234',
                acceptanceDate: '2026-05-09',
                deliveryAddress: 'Yerevan, Sayat-Nova 11, apt 9',
                model: 'Rocking armchair',
                dimensions: '75×80×105 sm',
                fabricType: 'Կտավ',
                softness: 'Շատ փափուկ',
                price: '55,000 ֏',
                advancePayment: '25,000 ֏',
                finalPayment: '30,000 ֏',
                notes: 'Khachakhagutyune prkovel hamar povrki vra',
                startDay: 9,
                endDay: 17,
            },

            // 8 · todo · Low
            {
                id: 't8',
                taskId: 'PN0001245',
                name: 'Divan modulayin — Simonyan R.',
                description: 'Shifon tsatskov, 3 modul, gerabezhaguyni',
                estimate: '6d',
                spentTime: '0d',
                loggedTime: '0d',
                originalEstimate: '6d',
                status: 'todo',
                section: 'active',
                priority: 'Low',
                group: 'Ս',
                assigneeColor: '#FF6B9D',
                assigneeInitials: 'NH',
                assigneeName: 'Nare Hakobyan',
                reporterName: 'Aram Petrosyan',
                reporterColor: '#4361EE',
                reporterInitials: 'AP',
                deadline: '2026-05-28',
                createdAt: '2026-05-15',
                client: 'Simonyan Ruzanna',
                phone: '+37499012345',
                acceptanceDate: '2026-05-15',
                deliveryAddress: 'Yerevan, Arshakunyats 18, apt 4',
                model: 'Modular sofa 3-section',
                dimensions: '300×100×85 sm',
                fabricType: 'Շիֆոն',
                softness: 'Փափուկ',
                price: '195,000 ֏',
                advancePayment: '100,000 ֏',
                finalPayment: '95,000 ֏',
                notes: 'Dastarakia petq e azatagrvel — hangecnel kliyenti het',
                startDay: 20,
                endDay: 28,
            },

            // ── BACKLOG ─────────────────────────────────────────────────────────────

            // 9 · backlog · todo · High
            {
                id: 't9',
                taskId: 'PN0001245',
                name: 'Banketka nakhsenyaki — Muradyan T.',
                description: 'Poliester tsatskov, kaghtsrayin, uzun',
                estimate: '1d',
                spentTime: '0d',
                loggedTime: '0d',
                originalEstimate: '1d',
                status: 'todo',
                section: 'backlog',
                priority: 'High',
                group: 'Ա',
                assigneeColor: '#96CEB4',
                assigneeInitials: 'AA',
                assigneeName: 'Artur Avetisyan',
                reporterName: 'Aram Petrosyan',
                reporterColor: '#4361EE',
                reporterInitials: 'AP',
                deadline: '2026-06-05',
                createdAt: '2026-05-15',
                client: 'Muradyan Tatevik',
                phone: '+37491122334',
                acceptanceDate: '2026-05-15',
                deliveryAddress: 'Yerevan, Isakov 30, apt 7',
                model: 'Hall bench with storage',
                dimensions: '120×40×50 sm',
                fabricType: 'Պոլիեսթեր',
                softness: 'Կոշտ',
                price: '28,000 ֏',
                advancePayment: '14,000 ֏',
                finalPayment: '14,000 ֏',
                notes: 'Parkin guyne hangecnel kliyenti het',
                startDay: 30,
                endDay: 35,
            },

            // 10 · backlog · todo · Medium
            {
                id: 't10',
                taskId: 'PN0001245',
                name: 'Mah koghov glukhavorov — Karapetyan N.',
                description: 'Metaks yzov, 160x200, antrasit guyn',
                estimate: '5d',
                spentTime: '0d',
                loggedTime: '0d',
                originalEstimate: '5d',
                status: 'todo',
                section: 'backlog',
                priority: 'Medium',
                group: 'Ա',
                assigneeColor: '#4361EE',
                assigneeInitials: 'AP',
                assigneeName: 'Aram Petrosyan',
                reporterName: 'Aram Petrosyan',
                reporterColor: '#4361EE',
                reporterInitials: 'AP',
                deadline: '2026-06-15',
                createdAt: '2026-05-15',
                client: 'Karapetyan Naira',
                phone: '+37492233445',
                acceptanceDate: '2026-05-15',
                deliveryAddress: 'Yerevan, Azatutyan 66, apt 2',
                model: 'Bed with upholstered headboard 160',
                dimensions: '160×200×120 sm',
                fabricType: 'Մետաքս',
                softness: 'Շատ փափուկ',
                price: '145,000 ֏',
                advancePayment: '70,000 ֏',
                finalPayment: '75,000 ֏',
                notes: 'Glukhavorov — karrotavarum, aranc pugaknerov',
                startDay: 36,
                endDay: 43,
            },
        ],
    },
];
