import type { EmployeeListItem } from './types';

export const employeesList: EmployeeListItem[] = [
  {
    id: '1',
    name: 'Aram Petrosyan',
    email: 'aram.petrosyan@gmail.com',
    gender: 'Male',
    birthday: 'Mar 14, 1985',
    fullAge: 41,
    position: 'Varapet',
    level: 'Senior',
    color: '#4361EE',
    initials: 'AP',
    tasks: { backlog: 1, inProgress: 3, inReview: 1 },
  },
  {
    id: '2',
    name: 'Nare Hakobyan',
    email: 'nare.hakobyan@gmail.com',
    gender: 'Female',
    birthday: 'Jun 22, 1992',
    fullAge: 33,
    position: 'Karogh',
    level: 'Middle',
    color: '#FF6B9D',
    initials: 'NH',
    tasks: { backlog: 0, inProgress: 4, inReview: 2 },
  },
  {
    id: '3',
    name: 'Karen Sargsyan',
    email: 'karen.sargsyan@gmail.com',
    gender: 'Male',
    birthday: 'Nov 08, 1988',
    fullAge: 37,
    position: 'Varapet',
    level: 'Senior',
    color: '#4ECDC4',
    initials: 'KS',
    tasks: { backlog: 2, inProgress: 3, inReview: 1 },
  },
  {
    id: '4',
    name: 'Ani Grigoryan',
    email: 'ani.grigoryan@gmail.com',
    gender: 'Female',
    birthday: 'Feb 17, 1995',
    fullAge: 31,
    position: 'Ktrogh',
    level: 'Middle',
    color: '#F0A500',
    initials: 'AG',
    tasks: { backlog: 1, inProgress: 5, inReview: 0 },
  },
  {
    id: '5',
    name: 'Artur Avetisyan',
    email: 'artur.avetisyan@gmail.com',
    gender: 'Male',
    birthday: 'Sep 03, 2003',
    fullAge: 22,
    position: 'Ashakert',
    level: 'Junior',
    color: '#96CEB4',
    initials: 'AA',
    tasks: { backlog: 0, inProgress: 2, inReview: 1 },
  },
  {
    id: '6',
    name: 'Lusine Martirosyan',
    email: 'lusine.martirosyan@gmail.com',
    gender: 'Female',
    birthday: 'Jul 30, 1990',
    fullAge: 35,
    position: 'Hashvarar',
    level: 'Senior',
    color: '#C39BD3',
    initials: 'LM',
    tasks: { backlog: 0, inProgress: 2, inReview: 1 },
  },
  {
    id: '7',
    name: 'Tigran Hovhannisyan',
    email: 'tigran.hovhannisyan@gmail.com',
    gender: 'Male',
    birthday: 'Apr 11, 1987',
    fullAge: 39,
    position: 'Varapet',
    level: 'Senior',
    color: '#82E0AA',
    initials: 'TH',
    onVacation: true,
    tasks: { backlog: 0, inProgress: 1, inReview: 0 },
  },
  {
    id: '8',
    name: 'Mariam Danielyan',
    email: 'mariam.danielyan@gmail.com',
    gender: 'Female',
    birthday: 'Jan 25, 1998',
    fullAge: 28,
    position: 'Ktrogh',
    level: 'Junior',
    color: '#F7DC6F',
    initials: 'MD',
    tasks: { backlog: 1, inProgress: 3, inReview: 1 },
  },
];

export const TOTAL_EMPLOYEES = 8;
export const PAGE_SIZE = 8;
